chore: Security Vulnerability Patch
qbcore-framework/qb-banking pull request #56
Opened 2022-04-27 02:30 UTC by uShifty

Adds a distance check to banks to ensure nobody is executing an event when they should not be. This will also create a log displaying the nearest bank to their current position.

2022-04-27 09:21 UTC, BerkieBb requested changes

2022-04-27 09:21 UTC, BerkieBb commented on server/main.lua
> +        if not returnData.nearestDistance then returnData.nearestDistance = distance elseif distance < returnData.nearestDistance then returnData.nearestDistance = distance end
Could you expand this if statement, it's not very readable for users now

2022-04-27 09:21 UTC, BerkieBb commented on server/main.lua
> +local validatePosition = function(coords)
```suggestion
local function validatePosition(coords)
```
This the syntax we use everywhere

2022-04-27 09:21 UTC, BerkieBb commented on server/main.lua
```suggestion
if not xPlayer then return end
```
A nil check for rare-cases where a cheater or a person is not registered in qb-core either through a bug or a weird cheat

2022-04-27 09:21 UTC, BerkieBb commented on server/main.lua
If you could, please add this check to every event there is

2022-04-27 09:21 UTC, BerkieBb commented on server/main.lua
>      while xPlayer == nil do Wait(0) end
Remove this while loop and make the if statement check which I added in the suggestion above

2022-04-27 09:21 UTC, BerkieBb commented on server/main.lua
>      while xPlayer == nil do Wait(0) end
Same for this one as the one above this

2022-04-27 09:21 UTC, BerkieBb commented on server/main.lua
>      while xPlayer == nil do Wait(0) end
And for this, etc.

2022-04-27 09:21 UTC, BerkieBb commented on server/main.lua
> +            while savings == nil do Wait(0) end
Please don't use while loops here as the variables are not getting assigned later anytime, if it is nil it stays nil, so please make a check like this `if not bank then return end` you can add a message to that check as well if you want

2022-04-27 09:21 UTC, BerkieBb commented on server/main.lua
> +        repeat Wait(0) until success ~= nil
Also no repeat statement needed here, just an if statemenf as said above for the while loops

2022-05-03 22:14 UTC, ItsANoBrainer approved these changes

2022-08-06 03:31 UTC, closed without merging